[package]
name = "uwnibook-color-typ"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["uwni"]
license = "MPL-2.0"
description = "A book template for my personal usage, with multilingual support"
categories = ["book"]
compiler = "0.13.1"

[template]
path = "boilerplate"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
